# Generated by Django 5.2.1 on 2025-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(default=0)),
                ("student_class", models.CharField(max_length=20)),
                (
                    "marks",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
        ),
    ]
